### ISSUE TITLE
pip install problem

### ISSUE THREAD

**Issue by dannyob** [rjhorniii/ical2org#27]
I get this error when trying `pip install ical2org`.

`Defaulting to user installation because normal site-packages is not writeable
Collecting ical2org
  Downloading ical2org-1.2.tar.gz (14 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [40 lines of output]
      Downloading http://pypi.python.org/packages/source/d/distribute/distribute-0.6.10.tar.gz
      Traceback (most recent call last):
        File "/tmp/pip-install-l06gb_g_/ical2org_1cfcb206d4524814a52a822f8bced0e7/distribute_setup.py", line 143, in use_setuptools
          raise ImportError
      ImportError
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-l06gb_g_/ical2org_1cfcb206d4524814a52a822f8bced0e7/setup.py", line 5, in <module>
          distribute_setup.use_setuptools()
        File "/tmp/pip-install-l06gb_g_/ical2org_1cfcb206d4524814a52a822f8bced0e7/distribute_setup.py", line 145, in use_setuptools
          return _do_download(version, download_base, to_dir, download_delay)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-install-l06gb_g_/ical2org_1cfcb206d4524814a52a822f8bced0e7/distribute_setup.py", line 123, in _do_download
          tarball = download_setuptools(version, download_base,
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-install-l06gb_g_/ical2org_1cfcb206d4524814a52a822f8bced0e7/distribute_setup.py", line 193, in download_setuptools
          src = urlopen(url)
                ^^^^^^^^^^^^
        File "/usr/lib/python3.11/urllib/request.py", line 216, in urlopen
          return opener.open(url, data, timeout)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/lib/python3.11/urllib/request.py", line 525, in open
          response = meth(req, response)
                     ^^^^^^^^^^^^^^^^^^^
        File "/usr/lib/python3.11/urllib/request.py", line 634, in http_response
          response = self.parent.error(
                     ^^^^^^^^^^^^^^^^^^
        File "/usr/lib/python3.11/urllib/request.py", line 563, in error
          return self._call_chain(*args)
                 ^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/lib/python3.11/urllib/request.py", line 496, in _call_chain
          result = func(*args)
                   ^^^^^^^^^^^
        File "/usr/lib/python3.11/urllib/request.py", line 643, in http_error_default
          raise HTTPError(req.full_url, code, msg, hdrs, fp)
      urllib.error.HTTPError: HTTP Error 403: SSL is required
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.`

**Comment by dannyob** [comment]
Oops! Wrong ical2org!
